// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy_uJbe6cglnkVGlKdATu9vAnF0mBzaJU',
    appId: '1:938712839227:android:9ce987d310cf4727d6581e',
    messagingSenderId: '938712839227',
    projectId: 'granth-d3cf5',
    storageBucket: 'granth-d3cf5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT4ttoU6sWyXyIZydgvyK6_qUlV9TbDaI',
    appId: '1:938712839227:ios:35038bd855cc39b8d6581e',
    messagingSenderId: '938712839227',
    projectId: 'granth-d3cf5',
    storageBucket: 'granth-d3cf5.firebasestorage.app',
    iosBundleId: 'com.example.granth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAI6-JawWoY6Xo3y3okN-UaoqFb-TwesI',
    appId: '1:938712839227:web:51e6c4efc50ab1e7d6581e',
    messagingSenderId: '938712839227',
    projectId: 'granth-d3cf5',
    authDomain: 'granth-d3cf5.firebaseapp.com',
    storageBucket: 'granth-d3cf5.firebasestorage.app',
  );
}
